spring.application.name: backend

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

# TODO: decrease to an hour and add refresh logic
security:
  jwt: ${JWT_SECRET}
  expiration-ms: 86400000

app:
  upload-dir: ${UPLOAD_DIR}
  base-url: ${BASE_URL}